#!/bin/bash

NAME="mrv_toolbox"
DJANGODIR=/home/helena/mrv-env/mrv
SOCKFILE=/home/helena/mrv-env/run/gunicorn.sock
USER=root
GROUP=web-group
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=mrv_toolbox.settings
DJANGO_WSGI_MODULE=mrv_toolbox.wsgi

cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django unicorn
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
